# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "禹过留声"
license = "MIT"
licenselink = "https://github.com/haojunyu/hugo-theme-hjy/blob/master/LICENSE"
description = "做一个合格的coder"
homepage = "https://blog.haojunyu.com"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "haojunyu"
  homepage = "https://blog.haojunyu.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
